### ISSUE TITLE
App crash courier modules not found

### ISSUE THREAD

**Issue by Arau** [sabith-th/kibana-csv-export#1]
Hi,

thank you @sabith-th for this project, I hope I can make it work. 

I used the instructions you mentioned to dockerise your code and run it on my kibana. I tried with: 

- 6.3.0
- 6.4.0
I couldn't use 6.8.0 because the elasticsearch in use is 6.4.0.

As soon as I run any HTTP request to Kibana, a 500 is thrown crashing the app. 

It indicates that some modules you are using are not found. Specifically the `courier` utils. I did some digging in the src of the application when running and I could find the courier directory but not as you specify in the includes. 

```
{"type":"error","@timestamp":"2020-01-07T11:49:58Z","tags":["fatal"],"pid":1,"level":"fatal","error":{"message":"Optimizations failure.\n   4050 modules\n    \n    \u001b[1m\u001b[31mERROR in ./src/ui/public/doc_table/doc_table.js\n    Module not found: Error: Can't resolve '../courier/utils/courier_inspector_utils' in '/usr/share/kibana/src/ui/public/doc_table'\u001b[39m\u001b[22m\n    \n    \u001b[1m\u001b[31mERROR in ./src/ui/public/doc_table/doc_table_strings.js\n    Module not found: Error: Can't resolve '@kbn/i18n' in '/usr/share/kibana/src/ui/public/doc_table'\u001b[39m\u001b[22m\n","name":"Error","stack":"Error: Optimizations failure.\n   4050 modules\n    \n    \u001b[1m\u001b[31mERROR in ./src/ui/public/doc_table/doc_table.js\n    Module not found: Error: Can't resolve '../courier/utils/courier_inspector_utils' in '/usr/share/kibana/src/ui/public/doc_table'\u001b[39m\u001b[22m\n    \n    \u001b[1m\u001b[31mERROR in ./src/ui/public/doc_table/doc_table_strings.js\n    Module not found: Error: Can't resolve '@kbn/i18n' in '/usr/share/kibana/src/ui/public/doc_table'\u001b[39m\u001b[22m\n\n    at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:245:27)\n    at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:28:26)\n    at onCompiled (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:241:12)\n    at applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:514:14)\n    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)\n    at Compiler.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/CachePlugin.js:78:5)\n    at Compiler.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)\n    at compilation.seal.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:511:11)\n    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:195:46)\n    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:671:19)\n    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:195:46)\n    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:662:11)\n    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)\n    at Compilation.<anonymous> (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/index.js:244:6)\n    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)\n    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:657:10)"},"message":"Optimizations failure.\n   4050 modules\n    \n    ERROR in ./src/ui/public/doc_table/doc_table.js\n    Module not found: Error: Can't resolve '../courier/utils/courier_inspector_utils' in '/usr/share/kibana/src/ui/public/doc_table'\n    \n    ERROR in ./src/ui/public/doc_table/doc_table_strings.js\n    Module not found: Error: Can't resolve '@kbn/i18n' in '/usr/share/kibana/src/ui/public/doc_table'\n"}
FATAL { Error: Optimizations failure.
   4050 modules
    
    ERROR in ./src/ui/public/doc_table/doc_table.js
    Module not found: Error: Can't resolve '../courier/utils/courier_inspector_utils' in '/usr/share/kibana/src/ui/public/doc_table'
    
    ERROR in ./src/ui/public/doc_table/doc_table_strings.js
    Module not found: Error: Can't resolve '@kbn/i18n' in '/usr/share/kibana/src/ui/public/doc_table'    at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:245:27)
    at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:28:26)
    at onCompiled (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:241:12)
    at applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:514:14)
    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)
    at Compiler.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/CachePlugin.js:78:5)
    at Compiler.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)
    at compilation.seal.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:511:11)
    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:195:46)
    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:671:19)
    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:195:46)
    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:662:11)
    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.<anonymous> (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/index.js:244:6)
    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:657:10)
  cause: 
   { Error: Optimizations failure.
   4050 modules
    
    ERROR in ./src/ui/public/doc_table/doc_table.js
    Module not found: Error: Can't resolve '../courier/utils/courier_inspector_utils' in '/usr/share/kibana/src/ui/public/doc_table'
    
    ERROR in ./src/ui/public/doc_table/doc_table_strings.js
    Module not found: Error: Can't resolve '@kbn/i18n' in '/usr/share/kibana/src/ui/public/doc_table'    at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:245:27)
    at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:28:26)
    at onCompiled (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:241:12)
    at applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:514:14)
    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)
    at Compiler.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/CachePlugin.js:78:5)
    at Compiler.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)
    at compilation.seal.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:511:11)
    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:195:46)
    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:671:19)
    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:195:46)
    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:662:11)
    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.<anonymous> (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/index.js:244:6)
    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:657:10)
     data: 
      { errors: [Array],
        warnings: [],
        version: '3.6.0',
        hash: '7a19cbb6038f94218262',
        time: 77616,
        publicPath: '__REPLACE_WITH_PUBLIC_PATH__',
        assetsByChunkName: [Object],
        assets: [Array],
        filteredAssets: 0,
        entrypoints: [Object],
        chunks: [Array],
        modules: [Array],
        filteredModules: 0,
        children: [Array] },
     isBoom: true,
     isServer: true,
     output: { statusCode: 500, payload: [Object], headers: {} },
     reformat: [Function],
     typeof: [Function] },
  isOperational: true,
  data: 
   { errors: 
      [ './src/ui/public/doc_table/doc_table.js\nModule not found: Error: Can\'t resolve \'../courier/utils/courier_inspector_utils\' in \'/usr/share/kibana/src/ui/public/doc_table\'\nresolve \'../courier/utils/courier_inspector_utils\' in \'/usr/share/kibana/src/ui/public/doc_table\'\n  using description file: /usr/share/kibana/package.json (relative path: ./src/ui/public/doc_table)\n    Field \'browser\' doesn\'t contain a valid alias configuration\n  after using description file: /usr/share/kibana/package.json (relative path: ./src/ui/public/doc_table)\n    using description file: /usr/share/kibana/package.json (relative path: ./src/ui/public/courier/utils/courier_inspector_utils)\n      no extension\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /usr/share/kibana/src/ui/public/courier/utils/courier_inspector_utils doesn\'t exist\n      .js\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /usr/share/kibana/src/ui/public/courier/utils/courier_inspector_utils.js doesn\'t exist\n      .json\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /usr/share/kibana/src/ui/public/courier/utils/courier_inspector_utils.json doesn\'t exist\n      as directory\n        /usr/share/kibana/src/ui/public/courier/utils/courier_inspector_utils doesn\'t exist\n[/usr/share/kibana/src/ui/public/courier/utils/courier_inspector_utils]\n[/usr/share/kibana/src/ui/public/courier/utils/courier_inspector_utils.js]\n[/usr/share/kibana/src/ui/public/courier/utils/courier_inspector_utils.json]\n[/usr/share/kibana/src/ui/public/courier/utils/courier_inspector_utils]\n @ ./src/ui/public/doc_table/doc_table.js 9:31-82\n @ ./src/ui/public/doc_table/index.js\n @ ./src/core_plugins/kibana/public/discover/embeddable/search_embeddable_factory.js\n @ ./src/core_plugins/kibana/public/discover/embeddable/search_embeddable_factory_provider.js\n @ ./optimize/bundles/kibana.entry.js',
        './src/ui/public/doc_table/doc_table_strings.js\nModule not found: Error: Can\'t resolve \'@kbn/i18n\' in \'/usr/share/kibana/src/ui/public/doc_table\'\nresolve \'@kbn/i18n\' in \'/usr/share/kibana/src/ui/public/doc_table\'\n  Parsed request is a module\n  using description file: /usr/share/kibana/package.json (relative path: ./src/ui/public/doc_table)\n    Field \'browser\' doesn\'t contain a valid alias configuration\n  after using description file: /usr/share/kibana/package.json (relative path: ./src/ui/public/doc_table)\n    resolve as module\n      /usr/share/kibana/src/ui/public/doc_table/webpackShims doesn\'t exist or is not a directory\n      /usr/share/kibana/src/ui/public/webpackShims doesn\'t exist or is not a directory\n      /usr/share/kibana/src/ui/webpackShims doesn\'t exist or is not a directory\n      /usr/share/kibana/src/webpackShims doesn\'t exist or is not a directory\n      /usr/share/webpackShims doesn\'t exist or is not a directory\n      /usr/webpackShims doesn\'t exist or is not a directory\n      /webpackShims doesn\'t exist or is not a directory\n      looking for modules in /usr/share/kibana/webpackShims\n        using description file: /usr/share/kibana/package.json (relative path: ./webpackShims)\n          Field \'browser\' doesn\'t contain a valid alias configuration\n        after using description file: /usr/share/kibana/package.json (relative path: ./webpackShims)\n          using description file: /usr/share/kibana/package.json (relative path: ./webpackShims/@kbn/i18n)\n            no extension\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/webpackShims/@kbn/i18n doesn\'t exist\n            .js\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/webpackShims/@kbn/i18n.js doesn\'t exist\n            .json\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/webpackShims/@kbn/i18n.json doesn\'t exist\n            as directory\n              /usr/share/kibana/webpackShims/@kbn/i18n doesn\'t exist\n      looking for modules in /usr/share/kibana/webpackShims\n        using description file: /usr/share/kibana/package.json (relative path: ./webpackShims)\n          Field \'browser\' doesn\'t contain a valid alias configuration\n        after using description file: /usr/share/kibana/package.json (relative path: ./webpackShims)\n          using description file: /usr/share/kibana/package.json (relative path: ./webpackShims/@kbn/i18n)\n            no extension\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/webpackShims/@kbn/i18n doesn\'t exist\n            .js\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/webpackShims/@kbn/i18n.js doesn\'t exist\n            .json\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/webpackShims/@kbn/i18n.json doesn\'t exist\n            as directory\n              /usr/share/kibana/webpackShims/@kbn/i18n doesn\'t exist\n      /usr/share/kibana/src/ui/public/doc_table/node_modules doesn\'t exist or is not a directory\n      /usr/share/kibana/src/ui/public/node_modules doesn\'t exist or is not a directory\n      /usr/share/kibana/src/ui/node_modules doesn\'t exist or is not a directory\n      /usr/share/kibana/src/node_modules doesn\'t exist or is not a directory\n      /usr/share/node_modules doesn\'t exist or is not a directory\n      /usr/node_modules doesn\'t exist or is not a directory\n      /node_modules doesn\'t exist or is not a directory\n      looking for modules in /usr/share/kibana/node_modules\n        using description file: /usr/share/kibana/package.json (relative path: ./node_modules)\n          Field \'browser\' doesn\'t contain a valid alias configuration\n        after using description file: /usr/share/kibana/package.json (relative path: ./node_modules)\n          using description file: /usr/share/kibana/package.json (relative path: ./node_modules/@kbn/i18n)\n            no extension\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/node_modules/@kbn/i18n doesn\'t exist\n            .js\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/node_modules/@kbn/i18n.js doesn\'t exist\n            .json\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/node_modules/@kbn/i18n.json doesn\'t exist\n            as directory\n              /usr/share/kibana/node_modules/@kbn/i18n doesn\'t exist\n      looking for modules in /usr/share/kibana/node_modules\n        using description file: /usr/share/kibana/package.json (relative path: ./node_modules)\n          Field \'browser\' doesn\'t contain a valid alias configuration\n        after using description file: /usr/share/kibana/package.json (relative path: ./node_modules)\n          using description file: /usr/share/kibana/package.json (relative path: ./node_modules/@kbn/i18n)\n            no extension\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/node_modules/@kbn/i18n doesn\'t exist\n            .js\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/node_modules/@kbn/i18n.js doesn\'t exist\n            .json\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/node_modules/@kbn/i18n.json doesn\'t exist\n            as directory\n              /usr/share/kibana/node_modules/@kbn/i18n doesn\'t exist\n[/usr/share/kibana/src/ui/public/doc_table/webpackShims]\n[/usr/share/kibana/src/ui/public/webpackShims]\n[/usr/share/kibana/src/ui/webpackShims]\n[/usr/share/kibana/src/webpackShims]\n[/usr/share/webpackShims]\n[/usr/webpackShims]\n[/webpackShims]\n[/usr/share/kibana/webpackShims/@kbn/i18n]\n[/usr/share/kibana/webpackShims/@kbn/i18n.js]\n[/usr/share/kibana/webpackShims/@kbn/i18n.json]\n[/usr/share/kibana/webpackShims/@kbn/i18n]\n[/usr/share/kibana/webpackShims/@kbn/i18n]\n[/usr/share/kibana/webpackShims/@kbn/i18n.js]\n[/usr/share/kibana/webpackShims/@kbn/i18n.json]\n[/usr/share/kibana/webpackShims/@kbn/i18n]\n[/usr/share/kibana/src/ui/public/doc_table/node_modules]\n[/usr/share/kibana/src/ui/public/node_modules]\n[/usr/share/kibana/src/ui/node_modules]\n[/usr/share/kibana/src/node_modules]\n[/usr/share/node_modules]\n[/usr/node_modules]\n[/node_modules]\n[/usr/share/kibana/node_modules/@kbn/i18n]\n[/usr/share/kibana/node_modules/@kbn/i18n.js]\n[/usr/share/kibana/node_modules/@kbn/i18n.json]\n[/usr/share/kibana/node_modules/@kbn/i18n]\n[/usr/share/kibana/node_modules/@kbn/i18n]\n[/usr/share/kibana/node_modules/@kbn/i18n.js]\n[/usr/share/kibana/node_modules/@kbn/i18n.json]\n[/usr/share/kibana/node_modules/@kbn/i18n]\n @ ./src/ui/public/doc_table/doc_table_strings.js 8:12-32\n @ ./src/ui/public/doc_table/doc_table.js\n @ ./src/ui/public/doc_table/index.js\n @ ./src/core_plugins/kibana/public/discover/embeddable/search_embeddable_factory.js\n @ ./src/core_plugins/kibana/public/discover/embeddable/search_embeddable_factory_provider.js\n @ ./optimize/bundles/kibana.entry.js' ],
     warnings: [],
     version: '3.6.0',
     hash: '7a19cbb6038f94218262',
     time: 77616,
     publicPath: '__REPLACE_WITH_PUBLIC_PATH__',
```

Do you have any idea or hint on how can I pass this?

Thank you!

**Comment by sabith-th** [comment]
Hi, I've created two new branches [6.3.0](https://github.com/sabith-th/kibana-csv-export/tree/6.3.0) and [6.4.0](https://github.com/sabith-th/kibana-csv-export/tree/6.4.0) which is compatible with the corresponding elasticsearch versions. Can you use the code from those branches and let me know if it works for you? 
PS: There were breaking changes from 6.3.x and 6.4.x to 6.8.x, which I forgot to mention in the README (I've done now). Thanks for letting me know.

**Comment by Arau** [comment]
Thank you very much! 

The changes allowed my to run kibana without exploding. The exports however are empty. The output of a report is only the timestamps, for instance:

```
"2019-10-07T01:40:50.257Z",
"2019-10-07T01:31:18.706Z",
"2019-10-06T01:40:50.228Z",
"2019-10-06T01:31:18.728Z",
"2019-10-05T01:40:50.273Z",
"2019-10-05T01:31:18.727Z",
"2019-10-04T01:40:50.258Z",
"2019-10-04T01:31:18.719Z",
"2019-10-03T01:40:50.230Z",
"2019-10-03T01:31:18.729Z",
"2019-10-02T01:40:50.235Z",
"2019-10-02T01:31:18.735Z",
"2019-10-01T01:40:50.274Z",
"2019-10-01T01:31:18.713Z",
"2019-09-30T01:40:50.259Z",
"2019-09-30T01:31:18.730Z",
"2019-09-29T01:40:50.249Z",
"2019-09-29T01:31:18.717Z",
"2019-09-28T01:40:50.247Z",
```

**Comment by sabith-th** [comment]
Did you select the fields you need in the discover tab? If you don't select the fields, it will be empty in the export

**Comment by Arau** [comment]
You are completely right, my mistake!

Thank you for your help!
